export {
  commentsReducer,
  setDeveloperAnswer,
  addComment,
  setAnswerDate,
  setAnswerText,
  setAuthorName,
  setAvatar,
  setCommentsText,
  setDeveloperName,
  setLikes,
  setRaiting,
  setReviewDate,
  removeComment,
  resetState,
  getAllComments,
  removeCommentById,
  createCommentHandler,
  type IUserComments,
} from "./model";
