export {
  commentsReducer,
  setDeveloperAnswer,
  addComment,
  setAnswerDate,
  setAnswerText,
  setAuthorName,
  setAvatar,
  setCommentsText,
  setDeveloperName,
  setLikes,
  setRaiting,
  setReviewDate,
  removeComment,
  resetState,
  getAllComments,
  removeCommentById,
  createCommentHandler,
  setComments,
  setAllComments,
  resetComment,
  setCommentGroupName,
} from "./model";

export type { AllComments, ReviewObject, CommentsList } from "./model"